"""phase1: complete schema (existing + new tables)

Revision ID: c31915475797
Revises: 
Create Date: 2026-07-10 11:15:49.117380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31915475797'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('ccd_price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('is_xd_card', sa.Boolean(), nullable=True),
    sa.Column('xd_card_bundle_count', sa.Integer(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ccd_price_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ccd_price_cache_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccd_price_cache_crawled_at'), ['crawled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccd_price_cache_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccd_price_cache_keyword'), ['keyword'], unique=True)

    op.create_table('crawl_keyword_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=True),
    sa.Column('risk_detected', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('debug_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'keyword', name='uq_crawl_keyword_batch_keyword')
    )
    with op.batch_alter_table('crawl_keyword_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_keyword_status_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_keyword_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_keyword_status_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_keyword_status_status'), ['status'], unique=False)

    op.create_table('crawl_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_keywords', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('bargains_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_status_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_crawl_status_id'), ['id'], unique=False)

    op.create_table('crawled_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('seller_id', sa.String(length=64), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('query_keyword', sa.String(length=256), nullable=True),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawled_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_items_item_id'), ['item_id'], unique=True)

    op.create_table('evaluation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('expected_models', sa.JSON(), nullable=True),
    sa.Column('expected_price_range', sa.JSON(), nullable=True),
    sa.Column('expected_risks', sa.JSON(), nullable=True),
    sa.Column('expected_tools', sa.JSON(), nullable=True),
    sa.Column('expected_path', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evaluation_cases_id'), ['id'], unique=False)

    op.create_table('global_bargains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('profit_estimate', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_xd_card', sa.Boolean(), nullable=True),
    sa.Column('xd_card_size', sa.String(length=32), nullable=True),
    sa.Column('xd_card_value', sa.Float(), nullable=True),
    sa.Column('card_status_uncertain_needs_confirm', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('refresh_batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_bargains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_bargains_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_bargains_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_bargains_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_global_bargains_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_bargains_profit_estimate'), ['profit_estimate'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_bargains_refresh_batch'), ['refresh_batch'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('embedding_version', sa.String(length=32), nullable=True),
    sa.Column('qdrant_status', sa.String(length=32), nullable=True),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_id'), ['id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'crawled_at', name='uq_price_history_keyword_crawled')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_crawled_at'), ['crawled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_keyword'), ['keyword'], unique=False)

    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('iqr_low', sa.Float(), nullable=True),
    sa.Column('iqr_high', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_observations_canonical_id'), ['canonical_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_observations_observed_at'), ['observed_at'], unique=False)

    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_aliases_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_aliases_canonical_id'), ['canonical_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_aliases_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('series', sa.String(length=64), nullable=True),
    sa.Column('sensor_type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('storage_types', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_canonical_id'), ['canonical_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_name'), ['name'], unique=False)

    op.create_table('valuation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('raw_prices', sa.Text(), nullable=True),
    sa.Column('deepseek_result', sa.Text(), nullable=True),
    sa.Column('qwen_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_records_id'), ['id'], unique=False)

    op.create_table('advisor_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_threads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_threads_thread_id'), ['thread_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_advisor_threads_user_id'), ['user_id'], unique=False)

    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('bargain_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation_record_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('profit_estimate', sa.Float(), nullable=True),
    sa.Column('xd_card_size', sa.String(length=32), nullable=True),
    sa.Column('xd_card_value', sa.Float(), nullable=True),
    sa.Column('card_status_uncertain_needs_confirm', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['valuation_record_id'], ['valuation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bargain_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bargain_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bargain_alerts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bargain_alerts_valuation_record_id'), ['valuation_record_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('passed_cases', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_run_id'), ['run_id'], unique=True)

    op.create_table('valuation_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation_record_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['valuation_record_id'], ['valuation_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_samples_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_samples_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_samples_valuation_record_id'), ['valuation_record_id'], unique=False)

    op.create_table('xianyu_auth_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('xianyu_account_label', sa.String(length=128), nullable=True),
    sa.Column('storage_state_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xianyu_auth_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xianyu_auth_bindings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xianyu_auth_bindings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_xianyu_auth_bindings_user_id'), ['user_id'], unique=True)

    op.create_table('advisor_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('requirement', sa.JSON(), nullable=True),
    sa.Column('target_models', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('langgraph_checkpoint_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['advisor_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_advisor_runs_thread_id'), ['thread_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('actual_models', sa.JSON(), nullable=True),
    sa.Column('actual_tools', sa.JSON(), nullable=True),
    sa.Column('actual_path', sa.JSON(), nullable=True),
    sa.Column('citation_correct', sa.Boolean(), nullable=True),
    sa.Column('price_consistent', sa.Boolean(), nullable=True),
    sa.Column('evidence_faithful', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trace_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_run_id'), ['run_id'], unique=False)

    op.create_table('advisor_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('evidence_correct', sa.Boolean(), nullable=True),
    sa.Column('price_accurate', sa.Boolean(), nullable=True),
    sa.Column('advice_adopted', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['advisor_runs.run_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_feedback_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_feedback_run_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_feedback_id'))

    op.drop_table('advisor_feedback')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_case_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('advisor_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_runs_thread_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_runs_id'))

    op.drop_table('advisor_runs')
    with op.batch_alter_table('xianyu_auth_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xianyu_auth_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_xianyu_auth_bindings_status'))
        batch_op.drop_index(batch_op.f('ix_xianyu_auth_bindings_id'))

    op.drop_table('xianyu_auth_bindings')
    with op.batch_alter_table('valuation_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_samples_valuation_record_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_samples_item_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_samples_id'))

    op.drop_table('valuation_samples')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('bargain_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bargain_alerts_valuation_record_id'))
        batch_op.drop_index(batch_op.f('ix_bargain_alerts_item_id'))
        batch_op.drop_index(batch_op.f('ix_bargain_alerts_id'))

    op.drop_table('bargain_alerts')
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_app_sessions_id'))

    op.drop_table('app_sessions')
    with op.batch_alter_table('advisor_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_threads_user_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_threads_thread_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_threads_id'))

    op.drop_table('advisor_threads')
    with op.batch_alter_table('valuation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_records_id'))

    op.drop_table('valuation_records')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_canonical_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_aliases_id'))
        batch_op.drop_index(batch_op.f('ix_product_aliases_canonical_id'))
        batch_op.drop_index(batch_op.f('ix_product_aliases_alias'))

    op.drop_table('product_aliases')
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_price_observations_id'))
        batch_op.drop_index(batch_op.f('ix_price_observations_canonical_id'))

    op.drop_table('price_observations')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_keyword'))
        batch_op.drop_index(batch_op.f('ix_price_history_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_crawled_at'))

    op.drop_table('price_history')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_document_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('global_bargains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_bargains_refresh_batch'))
        batch_op.drop_index(batch_op.f('ix_global_bargains_profit_estimate'))
        batch_op.drop_index(batch_op.f('ix_global_bargains_keyword'))
        batch_op.drop_index(batch_op.f('ix_global_bargains_item_id'))
        batch_op.drop_index(batch_op.f('ix_global_bargains_id'))
        batch_op.drop_index(batch_op.f('ix_global_bargains_brand'))

    op.drop_table('global_bargains')
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_case_id'))

    op.drop_table('evaluation_cases')
    with op.batch_alter_table('crawled_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_crawled_items_id'))

    op.drop_table('crawled_items')
    with op.batch_alter_table('crawl_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_status_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_status_batch_id'))

    op.drop_table('crawl_status')
    with op.batch_alter_table('crawl_keyword_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_keyword_status_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_keyword_status_keyword'))
        batch_op.drop_index(batch_op.f('ix_crawl_keyword_status_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_keyword_status_batch_id'))

    op.drop_table('crawl_keyword_status')
    with op.batch_alter_table('ccd_price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ccd_price_cache_keyword'))
        batch_op.drop_index(batch_op.f('ix_ccd_price_cache_id'))
        batch_op.drop_index(batch_op.f('ix_ccd_price_cache_crawled_at'))
        batch_op.drop_index(batch_op.f('ix_ccd_price_cache_brand'))

    op.drop_table('ccd_price_cache')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))
        batch_op.drop_index(batch_op.f('ix_app_users_id'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
